server: 
    port: 8081
eureka:
  client:
    serviceUrl:
       registerWithEureka: true
       fetchRegistry: false
       defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: CRUDSERVICE
    datasource:
        url: jdbc:mysql://localhost:3306/mydb
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root